### ISSUE TITLE
Set UI elements for the SOC

### ISSUE THREAD

**Issue by i-m-amit** [12rambau/sdg_indicators_module#14]
An extra input is required for the SOC function. The user needs to select an option from three choices :
- per pixel
- Specify a value from a list of  climate regimes (available in `parameter.py` as `climate_regime`)
- Custom: custom value

**Comment by 12rambau** [comment]
is it also for the 15.3.1 or does it need to be in another tile ?

**Comment by i-m-amit** [comment]
This is also part of 15.3.1. It does not need to be in another file. Just place it bellow the transition matrix.
