### ISSUE TITLE
code smell 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sdg_indicators_module#16]
Refactoring some of the SOC method code I faced a structure that smells  [run in L37](https://github.com/12rambau/sdg_indicators_module/blob/f1bb54f9aeab7087cb90f67b1f05a9d75b5e5add/indicators/15-3/15-3-1/scripts/run.py#L37) 

In this structure you checke twice if `year == 0`. My question is the following, is it normal that we don't perform the same thing ? 

- If yes then you should put it outside the for loop and start at `range(1, io.end-io.start)` to avoid the if tests at each loop.

- If not then then init of  `organic_carbon_change` and `lc_transition` should be done outside to make sure that every year have the same computation
____

**Illustration using arrays**

Instead of 
```py 
for i in range(10)
    if i == 0:
        toto = [f'fill {i}']
    else:
        toto.append(f'fill {i}')
```

You would prefer
```py
toto = []
for i in range(10)
    toto.append(f'fill {i}']
```

**Comment by i-m-amit** [comment]
I tried to fix the code smell by removing the `if` clause in the `for` loop. I still have some doubt on [These](https://github.com/12rambau/sdg_indicators_module/blob/d9b129531bf42ed23f888586bd7c901fa5a3d3ef/indicators/15-3/15-3-1/scripts/run.py#L51) lines of code. I have used the same lines  [here](https://github.com/12rambau/sdg_indicators_module/blob/d9b129531bf42ed23f888586bd7c901fa5a3d3ef/indicators/15-3/15-3-1/scripts/run.py#L102). What can be done to improve this section?

**Comment by 12rambau** [comment]
Based on the documentation, the `remap`method return the actual object so you don't need to create a tmp `lc_transition_climate_coef_temporary`

```py
lc_transition_climate_coef =  lc_transition \
    .remap(pm.IPCC_lc_change_matrix, pm.c_conversion_factor) \
    .where(lc_transition_climate_coef_temporary.eq(333),climate_conversion_coef) \
    .where(lc_transition_climate_coef_temporary.eq(-333), ee.Image(1).divide(climate_conversion_coef))
```
