### ISSUE TITLE
Issues with Sensors filtering

### ISSUE THREAD

**Issue by i-m-amit** [12rambau/sdg_indicators_module#17]
The filtering function does not provide the desired sensors. I should get all sensors available within the start and end years. For example, if I select start =1982 and end =2018, it returns only Landsat 4 instead of all the available sensors. The end year should be the current year.

**Comment by 12rambau** [comment]
## context 
When we talk about that with Yelena and Matieu, we decided taht the starting year will be the key to change the availability of sensors. 
What I have coded is doing the following when the start date is changed:
- clear the selected sensors
-  display the sensors that are available for the whole period

In your case 1982, the only available sensor was Landsat 4. 

## changes 
if it's not a problem for your workflow to have empty images, I can move the listener from the start date to the end date. Then the period you're looking at (1982-2018) will be covered by all sensors. 

Is it what you want me to change ?

**Comment by i-m-amit** [comment]
Ok, now I get the point.
However, this seems little problematic when I want to get a long term time series. We have to find out other options to avoid creating empty images. Don't change it now, I am testing all functions of the module. I will let you know what other things require changes. Then you can work on it tomorrow.
