### ISSUE TITLE
Shape of transition matrix 

### ISSUE THREAD

**Issue by i-m-amit** [12rambau/sdg_indicators_module#18]
I have two issues with the transition matrix

1. The output of the transition matrix is a nested list. However, the remap function of the ee needs a flat list. Can I change it by employing `chain.from_iterable(iterable)` method to the output of the matrix? Or do you suggest any other options?
2. Can we change the default values to a hardcoded matrix as follows?
```python
trans_matrix = [
[0, -1, -1, -1, -1, -1, 0], # Tree-covered
[1, 0, 1, -1, -1, -1, 0], # grassland
[1, -1, 0, -1, -1, -1, 0], # cropland
[-1, -1, -1, 0, -1, -1, 0], # wetland
[1, 1, 1, 1, 0, 1, 0], # artificial
[1, 1, 1, 1, -1, 0, 0,], # Other land
[0, 0, 0, 0, 0, 0, 0] # water body 
]
```

**Comment by 12rambau** [comment]
the `chain` component from `itertools` will return an iterator. I'm not sure that it is compatible with remap. 

instead what you can do is simply :
```python
trans_matrix_flatten = [item for sublist in trans_matrix for item in sublist]
```

the `trans_matrix_flatten` variable will be a list 

I'll work on the hardcoded transmatrix
