### ISSUE TITLE
add a legend on the map 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sdg_indicators_module#27]

**Comment by 12rambau** [comment]
I don't know what is display on the map and I'm not 100% convinced by the color choice. 
I suggest we add a legend to help end user understand what is displayed

**Comment by 12rambau** [comment]
can you just provide fill this table for me and will implement it in the code : 
| layer          | value                  | name                                                                        | color                                   |
|----------------|------------------------|-----------------------------------------------------------------------------|-----------------------------------------|
| the layer name | the value in the image | any useful or humanely understandable piece of information about the value  | the color you want to use in rgb or hex |

**Comment by i-m-amit** [comment]
All the layers contain same valuse (-1 = degraded,0 =stable,1=improved). The basic for calculating the final indicator is 'one out, all out'.
| layer           | value                  | name                                                                        | color                                   |
|-----------------|------------------------|-----------------------------------------------------------------------------|-----------------------------------------|
| productivity    | [-1, 0, 1]             | -1 : Degraded, 0: Stable, 1: Improved                                       | [#e9a3c9, #ffffbf, #a1d76a]             |
| land_cover      | [-1, 0, 1]             | -1 : Degraded, 0: Stable, 1: Improved                                       | [#d8b365, #d8b365, #5ab4ac]             |
| soc             | [-1, 0, 1]             | -1 : Degraded, 0: Stable, 1: Improved                                       | [#ef8a62, #ffffff, #999999]             |
| indicator_15_3_1| [-1, 0, 1]             | -1 : Degraded, 0: Stable, 1: Improved                                       | [#fc8d59, #ffffbf, #91cf60]             |

**Comment by 12rambau** [comment]
is it normal that colors for degraded and stable are the same for land cover ?

**Comment by i-m-amit** [comment]
No, it should not be the same. It was a typo. Change the stable color to  #fde0dd.

**Comment by 12rambau** [comment]
I let you give me a new tab ;-)

**Comment by 12rambau** [comment]
I've asked Matieu directly and I thing I get what we need now.
Sorry for bothering with the split of each map, that was actually useless
