### ISSUE TITLE
are all the trajectory functional ? 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sdg_indicators_module#29]
At the moment I only tested your code with following parameters :

- starting year : 2014
- start target period : 2015
- end year : 2018
- all available sensors
- trajectory : ndvi_trend
- default transition matrix
- default climate regime option

The available trajectories are : 
- ndvi_trend
- p_restrend
- s_restrend
- ue_trend

Are they functional or do I need to disabled them ?

**Comment by i-m-amit** [comment]
Disable the `s_restrend`, it is yet not implemented.
