### ISSUE TITLE
what is the remap_matrix ? 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sdg_indicators_module#3]
I refactor the code of the land_cover notebook to fit in the Sepal implementation. 

Everything is run from here : https://github.com/12rambau/sdg_indicators_module/blob/61a11f0492b271f90d196ebb02d2b1dea80bebb6/indicators/15-3/15-3-1/scripts/run.py#L7

based on what you coded I wire it with rest of the app but I get the following error we I run : 
> returned "Image.remap: From and to lists are not the same length.". Details: "Image.remap: From and to lists are not the same length."

I digged a bit in your code and I think the problem comes from the first 2 remapping. 

In your code you were doing the following : 
```py 
# Remap LC according to input matrix
    lc_remapped = lc.select('y{}'.format(year_baseline)).remap(remap_matrix[0], remap_matrix[1])
    for year in range(year_baseline + 1, year_target + 1):
        lc_remapped = lc_remapped.addBands(lc.select('y{}'.format(year)).remap(remap_matrix[0], remap_matrix[1]))
```

I was thinking that the `remap_matrix` was the `transition_matrix` it doesn't have the appropriate shape. Can you provide me with more information about this mysterious `remap_matrix` ?

**Comment by i-m-amit** [comment]
this remap is to translate the ESA land cover classes into IPPC classes. I have placed the matrix in the parameter file. As an improvement, we could use this feature along with a translation function to allow a user to put their own definition of land cover aggregation.
