### ISSUE TITLE
move from int16 to uint8 (bytes)

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sdg_indicators_module#36]
When downloading the images to sepal, the downloading speed is entirely related to the image coding and size. Our results have only 3 relevant value : 
- degraded: -1
- stable: 0
- improved: 1

It make no sense to use int16 to code that. 
I suggest we switch to uint8 to reduce the downloading time. 

THe value will thus need to change : 
- degraded: 1 
- stable: 2
- improved : 3
- nodata: 0

**Comment by i-m-amit** [comment]
Ok. I will make the neccessary changes.

**Comment by 12rambau** [comment]
I'm already on it
