### ISSUE TITLE
Can you provide a test area ? 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sdg_indicators_module#37]
Can you provide a test area that is small enought to compute fast (1 or 2 features) and provide results that satisfy you ?

The current testing area, is nearly degraded everywhere and I'm not sure that what we are computed make any sense. 

Cool thing would be to find a test area, and the provide me here the images I should obtain (you can simply drag&drop screenshots).
It will allow me to verify that my modifications (clipping, format, testing) don't alter the results

**Comment by i-m-amit** [comment]
`users/amitghosh/ER/IN/KillaiRF`
 
![Killai_pln](https://user-images.githubusercontent.com/12950330/106553609-b5a88f80-653f-11eb-9f38-0a04f472fc38.png)

The value/class over the the planted area should be 1(mproved)

![image](https://user-images.githubusercontent.com/12950330/106553527-8f82ef80-653f-11eb-90bb-cdcbd0b9f466.png)

**Comment by 12rambau** [comment]
Let's be precise : 
I need the dates to use, the matrix, the trajectory, and the climate coef (if needed)

Then, don't you have an area with at least 2 classes ? (i.e. improved and degraded)

**Comment by i-m-amit** [comment]
I am searching for such an area. Will update you soon.

**Comment by 12rambau** [comment]
Just updating what you send in you email : 
>Rashed has shared an AOI yesterday where we can find the states, degraded in 2017 and improve after 2018.
>asset id: users/amitghosh/ER/BD/AOI_Planet_vis

**Comment by i-m-amit** [comment]
I used the following parameters for Singapore
start: 2014
start year of the target period: 2016
end year:2018
sensors :[L4,L5,L7,L8]
trajectory: NDVI trend
default transition matrix
climate regime:per pixel based on global climate data

**Comment by 12rambau** [comment]
![Capture d’écran 2021-02-19 à 14 34 27](https://user-images.githubusercontent.com/12596392/108511185-d43cb380-72bf-11eb-9711-39b63b7fc78d.png)
