### ISSUE TITLE
What do you want to display in the final shapefile ? 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sdg_indicators_module#41]
At the moment the only output we get is a column named Class_sum which is not really helpful. 

What are the information you want to add in the final shapefile (count, mean...) ?

**Comment by i-m-amit** [comment]
The idea was to get the percentage of the area degraded/improve within a plot in the specified period. Instead of percentage, the out could be three columns with the area of a class (degraded/improved/stable) within a plot.

**Comment by 12rambau** [comment]
Ok I asked on the [github repository of geemap](https://github.com/giswqs/geemap/issues/283) and the `.shp` exportation is bugged in GEE. Our only option is to build the shapefile from the `.csv`. Which I did. 
I will let you adapt the code of the geemap function to export theses 3 columns you're talking about (at the moment I only get the Class_sum one) in percentage or sum as you prefer. I will adapt the code to write it in the `.shp` when it will be finished. 

before uo start anything, run `pip freeze | grep sepal-ui` in your terminal. If the version is lower than 1.0.3 then run `pip install sepal_ui==1.0.3` and it should run smoothly
