### ISSUE TITLE
sapefiles result columns doesn't reflect actual results 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sdg_indicators_module#47]
According to Rashed the final shapefile doesn't reflect the results of the computation (e.g. areas seems wrong) can you check on your side ?

**Comment by i-m-amit** [comment]
I did not find any issue with the area. I asked Rashed for more information on this.
![image](https://user-images.githubusercontent.com/12950330/109463164-92172d00-7a8a-11eb-97e1-dc41315fa05b.png)

**Comment by 12rambau** [comment]
I tested it on my side as well and I don't see any problem. Let's wait for his answer.

**Comment by 12rambau** [comment]
closing because no feedback were provided
