### ISSUE TITLE
missing description

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sdg_indicators_module#5]
I'm missing the description of the following functions which prevent me from understanding properly what they are doing, can you please update it ?

- [ ] productivity_trajectory (run.py, L105)
- [ ] p_restrend (productivity.py, L28)
- [ ] f_img_coll (productivity.py, l184)
- [ ] ue_trend (productivity.py, L57)
- [ ] productivity_performance (run.py, L159)
- [ ] productivity_state (run.py, L265)

**Comment by i-m-amit** [comment]
I have written the descriptions of the functions that were missing. Please approve the first the pull request, it is required to get the write access. 
Please take a look at the following figure to get an idea of the structure of the module. 
![sdg_15_3_1](https://user-images.githubusercontent.com/12950330/102208857-f39d1600-3ef5-11eb-8015-b2fb49d85f00.png)

**Comment by 12rambau** [comment]
excellent, lets keep this drawing for documentations !
