### ISSUE TITLE
Load indicator error

### ISSUE THREAD

**Issue by adebowaledaniel** [12rambau/sdg_indicators_module#62]
Hello, 
After providing all necessary parameter I got error message: productivity_state() missing 1 required positional argument: 'output'. Can you help look into it, please? 
![image](https://user-images.githubusercontent.com/20906703/134912833-292693ee-7795-4787-bd0e-951550c10409.png)

**Comment by 12rambau** [comment]
Can you provide all the parameters you used so that I can reproduce your error from my side ?

**Comment by adebowaledaniel** [comment]
AOI = users/aadebowaledaniel/RM/Jigawa (Jigawa state, Nigeria; gee asset)
Historical period (start, end) - (2015, 2016)
Monitoring period (start, end) - (2017,2020)
Sensor - Sentinel 2
Trajectory - NDVI trend
Transition matrix - default
Climate regime options - Per-pixel based on global climate data

**Comment by 12rambau** [comment]
I' in contract break so not working 100% on SEPAL related stuff so if this issue is still unsolved no worries I'll have a look when I'll be back.
I you close it because you found a solution from your side, I'm happy to leave it closed
