### ISSUE TITLE
the legend of the land cover maps i not set on the map 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sdg_indicators_module#70]
Here again the color legend should be display to the user on the map and as an exportation outut (pdf).

@i-m-amit could you describe it to me or link me to the source so tht I can update the map display ?

**Comment by i-m-amit** [comment]
The colour is the same used for the sankey plot [L51 in ui.py](https://github.com/12rambau/sdg_indicators_module/blob/8077667f65b5de916af06a917fa065df9aa99b8f/component/parameter/ui.py#L51).

**Comment by 12rambau** [comment]
I used a truncated version of the original cci colormap
