### ISSUE TITLE
use a download button within the map to choose what to export

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sdg_indicators_module#72]
In the current implementation the end_user doesn't know what is exported and in which order. He may not need all the informations at once

**Comment by i-m-amit** [comment]
In majority of the cases an end user/reporting agency needs nearly all the information to prepare a report as mentioned in the GPG. So, It would be easier to have only one Botton to download all the results. what do you think?

**Comment by 12rambau** [comment]
with the graphs and the extra legend I think there is not enough space for the button in the map
closing it as wontfix
